% Test for Trajectory Generator
clear;
clc;

global l1 l2 l3 vital_radius vital_x vital_y vital_center sensor_radius;

% Robot parameters (to avoid issues in downstream tests)
l1 = 1.0; % Link 1 length
l2 = 1.0; % Link 2 length
l3 = 0.3; % Link 3 length

% Vital area parameters
vital_radius = 0.2;
vital_x = 0.0;
vital_y = 0.0;
vital_center = [vital_x; vital_y];
sensor_radius = vital_radius * 5.5; % Detect 50% earlier


% Generate trajectory points for a range of times
t_total = 10; % Total simulation time
dt = 0.1; % Time step
time = 0:dt:t_total;

% Storage for trajectory points
trajectory_points = zeros(2, length(time));

% Generate and plot trajectory
for i = 1:length(time)
    trajectory_points(:, i) = trajectory_generator3_1(time(i));
end

% Plot the trajectory
figure;
hold on;
viscircles([vital_x, vital_y], vital_radius, 'LineStyle', '--', 'Color', 'r');
plot(trajectory_points(1, :), trajectory_points(2, :), 'b-', 'LineWidth', 2);
title('Trajectory Generated by trajectory\_generator3\_1');
xlabel('X Position (m)');
ylabel('Y Position (m)');
grid on;
axis equal;

% Test for Inverse Kinematics
clear;
clc;

% Test positions (modify these to check edge cases)
test_positions = [
    1.0, 0.5;
    0.5, 0.5;
    0.75, 0.1;
];

% Loop through positions
for i = 1:size(test_positions, 1)
    x = test_positions(i, 1);
    y = test_positions(i, 2);
    fprintf('Testing position (%.2f, %.2f):\n', x, y);
    try
        q = InverseKinematics([x; y]);
        fprintf('Joint angles: q1 = %.2f, q2 = %.2f, q3 = %.2f\n\n', q(1), q(2), q(3));
    catch ME
        fprintf('Error: %s\n\n', ME.message);
    end
end

%Test for Forward Kinematics
% Test joint angles (modify these to check different configurations)
test_angles = [
    pi/6, pi/4, pi/3;
    pi/3, pi/6, pi/4;
    pi/4, pi/3, pi/6;
];

% Loop through joint angle sets
for i = 1:size(test_angles, 1)
    q1 = test_angles(i, 1);
    q2 = test_angles(i, 2);
    q3 = test_angles(i, 3);
    fprintf('Testing angles (q1 = %.2f, q2 = %.2f, q3 = %.2f):\n', q1, q2, q3);
    result = ForwardKinematics3([q1; q2; q3]);
    fprintf('End-effector position: x = %.2f, y = %.2f\n\n', result(1), result(2));
end

%Test for plot
% Test joint angles
test_angles = [
    pi/6, pi/4, pi/3;
    pi/3, pi/6, pi/4;
    pi/4, pi/3, pi/6;
];

figure;
hold on;
global vital_x vital_y vital_radius
viscircles([vital_x, vital_y], vital_radius, 'LineStyle', '--', 'Color', 'r');
for i = 1:size(test_angles, 1)
    q1 = test_angles(i, 1);
    q2 = test_angles(i, 2);
    q3 = test_angles(i, 3);
    DisplayRobot3([q1; q2; q3];[x1;x2]);
end
title('Robot Configuration');
xlabel('X Position (m)');
ylabel('Y Position (m)');
grid on;
axis equal;